version: "3.9"
services:
  redis1:
    container_name: redis1
    image: 'redis:latest'
    ports:
      - '6379:6379'
    restart: always
    command: redis-server 
  redis2:
    container_name: redis2
    image: 'redis:latest'
    ports:
      - '6380:6379'
    restart: always
    command: redis-server 
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - data:/db
volumes:
  data:     