version: "3.9"
services:
  application:
    build: .
    env_file: ".env.development"
    container_name: application
    ports:
      - "3000:3000"
    depends_on:
      - redis1
      - redis2
      - mongodb
    restart: always
    networks:
      - node-network
  redis1:
    container_name: redis1
    image: "redis:latest"
    restart: always
    command: redis-server #--port 6380
    networks:
      - node-network
  redis2:
    container_name: redis2
    image: "redis:latest"
    # ports:
    #   - '6380:6379'
    restart: always
    command: redis-server --port 6381
    networks:
      - node-network
  mongodb:
    image: mongo:6-jammy
    # ports:
    #   - '27017:27017'
    volumes:
      - data:/db
    networks:
      - node-network
volumes:
  data:
networks:
  node-network:
    driver: bridge
